### PR TITLE
Principal members of types must not be used in other types.

### PR DESCRIPTION
**Pull request by sgillies**
List discussion: https://mailarchive.ietf.org/arch/msg/geojson/eVZbpxrORyt5koH6P7QjdcfcRHE.

### CODE REVIEW

**Comment by tschaub** [comment]
Looks good to me.

**Comment by mpdaly** [comment]
:+1:

**Comment by sgillies** [comment]
@tschaub @mpdaly thanks for the quick feedback! I've got one more question I'm going to ask in the email thread.

**Comment by sgillies** [comment]
In 45814c3, I attempt to do what I said I would on the list. @dret @sdrees does it look right to you? I think it needs better wording. I'm open to suggestions.

> Allan,
> 
> That's not disallowed, but I'm working on text that makes it clear that
> since "foo" is a foreign property, GeoJSON semantics do not apply under it.
> It's not a Feature object, no matter that it is structured like one.

**Comment by dret** [comment]
what about changing the heading from "Semantics of GeoJSON members and types are not extensible" to "Semantics of GeoJSON members and types are not changeable"? after all, it is possible to extend  semantics with additional members, and that is fine, as long as none of the basic GeoJSON semantics are changed.

**Comment by sgillies** [comment]
This is good to go. I'll merge later today if there are no objections.

**Comment by mpdaly** [comment]
I'm feeling bad now that we've banned FeatureCollection from having a "properties" member, but not bad enough to stand in the way of progress.

**Pull request merged**
