### PR TITLE
Change "SHOULD" to "should" in 10.4

### PR DESCRIPTION
**Pull request by tschaub**
This follows the suggestions from [Alissa Cooper's email](https://mailarchive.ietf.org/arch/msg/geojson/dK5vSfGSXCuWR7QkzQulk2yicMs).  I'll admit I don't understand the nuance here, but am curious to understand.

Note that we still have other RFC2119 key words in the considerations sections (including SHOULD).

### CODE REVIEW

**Comment by sgillies** [comment]
As I said in a response to that email, I'd like to keep SHOULD. There are very few applications that can properly handle features that aren't cut at the anti-meridian.

**Comment by coopdanger** [comment]
As I said in email, no problem with normative SHOULD, but that should be stated as a generic requirement, not within examples.

**Comment by sgillies** [comment]
@coopdanger Ah, I think I understand now. I think there are 2 ways to go.

1. I'll propose on the list that we move the text of [10.5 Interop Considerations/Geometry Collections](https://tools.ietf.org/html/draft-ietf-geojson-02#section-10.5) to [3.1.8 Geometry Object/Geometry Collections](https://tools.ietf.org/html/draft-ietf-geojson-02#section-3.1.8), wholesale, and transport the text of [10.4](https://tools.ietf.org/html/draft-ietf-geojson-02#section-10.4) to 3.1 (becoming 3.1.9). This would let us keep the normative language.

2. If there's no consensus for this, we can change the normative language in the Interop Considerations, leaving them otherwise as they are.

Sound like a plan? /cc @tschaub @martinthomson @dret

**Comment by martinthomson** [comment]
WFM

**Comment by sgillies** [comment]
Superseded by #195.

**Comment by sgillies** [comment]
@tschaub I need clarification: are you now more in favor of this one than in favor of #195?

**Comment by tschaub** [comment]
I understand now the issue of avoiding normative language in examples.  I like that this change is simpler than #195.  So reopening and merging this makes sense to me.

@sgillies if you feel strongly that some of the interoperability considerations should become normative recommendations, you could continue on #195 (and it also seems like the sections don't necessarily need to be reorganized, but rather the normative language would have to come out of the examples).

**Pull request closed without merging**
