### PR TITLE
Promote antimeridian and geometry collection sections

### PR DESCRIPTION
**Pull request by sgillies**
As proposed in https://mailarchive.ietf.org/arch/msg/geojson/aS9PoHDDrZ64uIoWm9S2FLjzXiU.

> Hi all,
> 
> To address a comment from our AD, I would like to do one of the following:
> 
> 1. Move the text of 10.5 Interop Considerations/Geometry Collections to
> 3.1.8 Geometry Object/Geometry Collections, wholesale, and transport the
> text of 10.4 to 3.1 (becoming 3.1.9). This would let us keep the normative
> language.
> 
> 2. If there's no consensus for this, we can change the normative language
> in the Interop Considerations, leaving them otherwise as they are.
> 
> Any objections to the first option?

### CODE REVIEW

**Comment by tschaub** [comment]
This looks good to me.

**Comment by coopdanger** [comment]
The re-organization is fine but the normative language still needs to come out of the examples and into a generic statement. What you want, I think, is something like:

In representing features that cross the antimeridian, interoperability is improved by cutting geometries so that no single part crosses the antimeridian. Any feature that crosses the antimeridian SHOULD be represented by cutting it in two such that neither of the two object representations crosses the antimeridian. For example, a line extending from 45 degrees N, 170 degrees E across the antimeridian to 45 degrees N, 170 degrees W should be cut in two and represented as a MultiLineString. ... A rectangle extending from 40 degrees N, 170 degrees E across the antimeridian to 50 degrees N, 170 degrees W should be cut in two and represented as a MultiPolygon.

**Comment by dr-shorthair** [comment]
Wow. Clearly no-one from NZ or Fiji in this team!

**Comment by sgillies** [comment]
@dr-shorthair we're so close... I'd appreciate it if everybody would keep their snark to themselves for a few more days! :bow:

**Comment by sgillies** [comment]
@coopdanger thanks! I like how this reads now.

@tschaub cool with the above? I've gone back and forth but would like to go ahead with this one over #194.

**Comment by tschaub** [comment]
@sgillies this works for me too.

**Comment by dr-shorthair** [comment]
Sorry - it was a bit snarky. 

But there is a concern here - Fiji may not be a big market, but having to cut it in two ain't great. 
New Zealand is a bit bigger. The anti-meridian is offshore, but still in territorial area. 

Was this rule always there for geometry? I recall the bounding-box discussion a couple of months ago did not require splitting on the anti-meridian (or did I lose track of that too?)

**Comment by martinthomson** [comment]
A bounding box cannot be split, so I think that it's moot.

You could say that as long as you hide the split well enough by having good tools, your users won't actually see the split.  Maybe this is a bit of unpleasantness that software can handle for us so that we can get the benefits of usability and interoperability.

**Pull request merged**
