### PR TITLE
minor changes

### PR DESCRIPTION
**Pull request by dret**
mostly wording, and leaving open the possibility to add JSON text
sequences to the spec.

### CODE REVIEW

**Comment by sgillies** [comment]
:+1: I'd forgotten that we'd need to add GeoJSON text sequences to the charter.

**Comment by dret** [comment]
just a precaution. ready to go now? i like it!

**Comment by sgillies** [comment]
Me, too. Close #65 when you've sent it.

**Comment by adoyle** [comment]
+1

**Comment by dret** [comment]
done, message sent and awaiting moderator approval. keep an eye on http://www.ietf.org/mail-archive/web/dispatch/current/maillist.html

**Comment by dret** [comment]
@sgillies, i don't think i can close issues. so you'll have to do that.

**Comment by dret** [comment]
http://www.ietf.org/mail-archive/web/dispatch/current/msg05795.html

**Pull request merged**
