### PR TITLE
Positions are not a point of extension

### LINKED ISSUE #56: Make position extensions discoverable
for positions, this is the current draft language: "Additional position elements MAY be included but MUST follow the three specified above and MAY be ignored by software. Interpretation and meaning of additional elements is beyond the scope of this specification."
i am wondering whether it was ever brought up to be able to identify these additional elements? it probably would be possible to add some metadata somewhere that would probably contain URIs, which could then be interpreted as the "metadata label" for any position element beyond the three standard ones. then i could have positions with five elements, and i would be able to tell that the fourth element would be heart rate data, and the fifth would be power data.
it seems to me that adding this should be able without breaking backwards compatibility, and it would make interpretation of GeoJSON using additional position elements much more robust.

### LINKED ISSUE #57: can position "extensions" be non-number values?
the spec currently says the following about values in positions past the three specified elements of long, lat, and elevation:

> Additional position elements MAY be included but MUST follow the three specified above and MAY be ignored by software. Interpretation and meaning of additional elements is beyond the scope of this specification.

this seems to allow non-number values. but then again, the text about positions in general says it's "an array of numbers". so the question is: can i have non-number values past the third position? specifically, i am wondering if the following is legal position or not:
```
        [
          -122.45698875747621,
          37.78691156767309,
          138.1999969482422, 
          NULL
        ]
```
it would be good to clarify the language so that it's clear whether non-number values are allowed or not.

### PR DESCRIPTION
**Pull request by sgillies**
Email thread: https://mailarchive.ietf.org/arch/msg/geojson/wfb6Nd0nEHW70EfZmdtvfC0stfQ

Closes #56
Closes #57

### CODE REVIEW

**Comment by sgillies** [comment]
Consensus +1 on the list. I've addressed @dret's comment about error reporting implications of making positions non-extensible by removing that section.

**Comment by dret** [comment]
because of the title: is there a single place that lists all points of extension? i am still a bit confused whether there are some "blessed" extension points (which implementations that should expose instead of silently ignoring), or is the model the "everything goes as long as it's JSON"? should that be a specific issue? i'd be happy to raise it if it still is an open question...

**Comment by sgillies** [comment]
@dret Any foreign JSON property (a key and value), anywhere, has our blessing. But that's the only kind of extension we bless. Should we state this plainly in the "Foreign properties" section under "Extending GeoJSON"?

**Comment by dret** [comment]
On 2015-12-06 21:55 , Sean Gillies wrote:
> @dret <https://github.com/dret> Any foreign JSON property (a key and
> value), anywhere, has our blessing. But that's the only kind of
> extension we bless. Should we state this plainly in the "Foreign
> properties" section under "Extending GeoJSON"?

i am getting a bit confused now. i can put anything anywhere and that's 
fine? any constraint/guidance on the key name or the value type? if not, 
what does "But that's the only kind of extension we bless." mean?

i know that this is controversial, but many formats i have worked with 
are less permissive and have specific extension points. the advantages 
of this are:

- well-meaning developers looking for where to put extension data find 
guidance that helps them to put it in "good places".

- validation tools like geojsonlint can be used to make sure that some 
GeoJSON follows these guidelines. this is assuming that geojsonlint 
would be updated to identify "strict GeoJSON" (only core data), 
"extended GeoJSON" (only using extension points), and "unkosher GeoJSON" 
(using extensions outside the blessed extension points).

- toolbox developers know where to look for extension data so that they 
can expose it (or make it available) in their toolboxes.

- well-meaning developers following the extension guidance are more 
likely that their GeoJSON can be used well in those toolboxes.

i do understand that there is no mechanism to *force* anybody to only 
use these extension points. but that's not the goal to begin with.

the goal is to promote an ecosystem that can develop and thrive, but to 
allow that to happen in less-than-random ways. if people prefer random 
ways, they can still do it, but they will be locked out of the 
advantages listed above.

**Comment by sgillies** [comment]
@dret I'm not feeling much potential for consensus on specific extension points and am not prepared to craft any specific proposal that might attract consensus. I could get behind a good proposal, but don't have one of my own. At the moment, GeoJSON is pretty much on par with Atom – foreign properties allowed anywhere they are not explicitly forbidden – no?

**Comment by dret** [comment]
On 2015-12-16 15:14 , Sean Gillies wrote:
> @dret <https://github.com/dret> I'm not feeling much potential for
> consensus on specific extension points and am not prepared to craft any
> specific proposal that might attract consensus. I could get behind a
> good proposal, but don't have one of my own. At the moment, GeoJSON is
> pretty much on par with Atom – foreign properties allowed anywhere they
> are not explicitly forbidden – no?

i'd say atom is very different, and in a good way. the grammar 
explicitly mentions extensions where allowed, so if you just take the 
grammar you get a parser that accepts allowed extensions and rejects 
them anywhere else.

also, it says what to do when atom elements are encountered in places 
where they are not expected (according to the grammar). i may have 
mentioned before (;-) that i am huge fan of processing models, since i 
think they give developers the best chance to achieve interop, if they 
are trying to do so. no indirect exegesis of language that's scattered 
throughout the spec, but everything that matters in one place.

http://tools.ietf.org/html/rfc4287#section-4.1.3.3

**Pull request merged**
