### PR TITLE
Remove section concerning URIs

### LINKED ISSUE #105: some paragraphs were replaced during porting from XML to Markdown
This [commit](https://github.com/geojson/draft-geojson/commit/66b7942d75a906a3fce785e5c3dbc818707e96cd) replaces some paragraphs.
For example following paragraph was removed

```
On encountering a named CRS object with a value of
"urn:ogc:def:crs:OGC:1.3:CRS84" or
"http://www.opengis.net/def/crs/OGC/1.3/CRS84", processors SHOULD
interpret the coordinates exactly as in Section 2.1.1; these CRS are
equivalent to the default coordinate reference system.
```

It looks like this was caused by copy-pasting from some old version.

### PR DESCRIPTION
**Pull request by sgillies**
This is not really the draft's business anymore. Moreover, a cut and paste error made this section nonsensical.

Closes #105

### CODE REVIEW

**Comment by dret** [comment]
thanks, this does indeed address #105, i think this is ready to be merged.

**Comment by sgillies** [comment]
@dret @martinthomson shall I upload a new version of draft-butler-geojson (-07) with this fix before we adopt?

**Comment by martinthomson** [comment]
This is a change we can take in a -00 working group draft. I expect to close the call for adoption soon.

**Comment by sgillies** [comment]
To be merged after we close #106.

**Comment by tschaub** [comment]
Looks good to me.

**Pull request merged**
