### PR TITLE
Correct orientation of example rings

### LINKED ISSUE #231: Examples in appendix have wrong orientation
The no-hole Polygon 

```
      {
          "type": "Polygon",
          "coordinates": [
              [
                  [100.0, 0.0],
                  [100.0, 1.0],
                  [101.0, 1.0],
                  [101.0, 0.0],
                  [100.0, 0.0]
              ]
          ]
      }
```

winds clockwise and should be fixed.

The example with holes

```
      {
          "type": "Polygon",
          "coordinates": [
              [
                  [100.0, 0.0],
                  [100.0, 1.0],
                  [101.0, 1.0],
                  [101.0, 0.0],
                  [100.0, 0.0]
              ],
              [
                  [100.8, 0.8],
                  [100.2, 0.8],
                  [100.2, 0.2],
                  [100.8, 0.2],
                  [100.8, 0.8]
              ]
          ]
      }
```

has the same problem plus a hole that winds counterclockwise (wrong).

The multipolygon examples are also wrong.

### PR DESCRIPTION
**Pull request by sgillies**
Resolves #231

### CODE REVIEW

**Comment by sgillies** [comment]
@tschaub @adoyle @hobu @mpdaly @sdrees the rings in our polygon examples were oriented contrary to the guidance in our spec and I've made them consistent. I'd like to write the RFC Editor on behalf of every author and ask them to make the change. Okay?

/cc @martinthomson @dret

**Comment by adoyle** [comment]
+1 -  We're lucky this was discovered at this stage, not later.

	Allan

**Comment by hobu** [comment]
+1

**Comment by tschaub** [comment]
Thanks @sgillies.

**Comment by sgillies** [comment]
My eyes and brain being unreliable, I used Shapely to test the new GeoJSON and verify that exterior rings are ccw, interior rings are cw, and that the signed areas are as we'd expect: positive for exterior rings, negative for holes.

**Pull request merged**
