### PR TITLE
Circle CI draft builds

### PR DESCRIPTION
**Pull request by sgillies**
Goal: run the draft text/html/etc build on Circle CI for every commit.

### CODE REVIEW

**Comment by sgillies** [comment]
@martinthomson @dret here we go, Circle CI building for us.

**Comment by martinthomson** [comment]
:+1:

**Comment by tschaub** [comment]
Nice @sgillies.

**Comment by dret** [comment]
sweet! time for me to look into the current crop of github CI tools, circle is a new one for me.

**Pull request merged**
